# -*- coding: utf-8 -*-
"""EPPQ-MDMC-baseline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vv_7Oq6gRVKvC9aZ05BxfzHZyuo9H5la
"""

# =============================================================================
# EPPQ λ-VALIDATION PIPELINE (VERSÃO CORRIGIDA - TERMODINÂMICA BOLTZMANN)
# =============================================================================

import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
from tqdm import tqdm

# -----------------------------------------------------------------------------
# 1. Simulação da Dinâmica PMAH (Metropolis-Hastings com Temperatura)
# -----------------------------------------------------------------------------

def pmah_vacuum_generator(N, m, lambda_val, steps=8000, T=2.0, seed=42):
    """
    T: Temperatura termodinâmica do banho. Controla o quão fácil o grafo
       pode aceitar trocas que pioram momentaneamente a energia para evitar mínimos locais.
    """
    np.random.seed(seed)

    # Inicializa BA
    G = nx.barabasi_albert_graph(N, m, seed=seed)
    target_degrees = {node: deg for node, deg in G.degree()}

    for (i, j) in G.edges():
        G[i][j]['c'] = np.random.uniform(0, 1)
        G[j][i]['c'] = G[i][j]['c']

    root = 0
    try:
        historical_depth = nx.shortest_path_length(G, source=root)
        h = np.array([historical_depth.get(i, np.inf) for i in range(N)])
    except:
        h = np.full(N, np.inf)
        h[root] = 0

    for step in tqdm(range(steps), desc=f"PMAH λ={lambda_val:.2f}"):
        i = np.random.randint(0, N)

        if G.degree(i) > 0:
            j = np.random.choice(list(G.neighbors(i)))
            neighbors_of_j = list(G.neighbors(j))
            if len(neighbors_of_j) > 1:
                k = np.random.choice([x for x in neighbors_of_j if x != i])

                # Custo Histórico
                current_h_i = h[i]
                new_h_i_est = min(current_h_i, h[k] + 1, h[j] + 1)
                delta_C = max(0, new_h_i_est - current_h_i)

                # Custo de Interface
                deg_j = G.degree(j)
                deg_k = G.degree(k)
                target_j = target_degrees[j]
                target_k = target_degrees[k]

                cost_j_old = (deg_j - target_j)**2
                cost_j_new = (deg_j - 1 - target_j)**2
                cost_k_old = (deg_k - target_k)**2
                cost_k_new = (deg_k + 1 - target_k)**2
                delta_I = (cost_j_new - cost_j_old) + (cost_k_new - cost_k_old)

                # Variação total da Ação
                delta_A = delta_I + lambda_val * delta_C

                # Aceitação de Boltzmann rigorosa
                if delta_A < 0 or np.random.rand() < np.exp(-delta_A / T):
                    G.remove_edge(i, j)
                    G.add_edge(i, k)
                    G[i][k]['c'] = np.random.uniform(0, 1)
                    G[k][i]['c'] = G[i][k]['c']

                    try:
                        new_h = nx.shortest_path_length(G, source=root)
                        h = np.array([new_h.get(v, np.inf) for v in range(N)])
                    except:
                        pass

    degrees = np.array([deg for _, deg in G.degree()])
    mean_deg = np.mean(degrees)

    k_min = np.percentile(degrees, 75)
    tail_degrees = degrees[degrees >= k_min]

    if len(tail_degrees) > 3 and k_min > 0:
        gamma_est = 1.0 + len(tail_degrees) / np.sum(np.log(tail_degrees / k_min))
        beta_est = gamma_est - 1.0
    else:
        beta_est = 1.6

    return G, beta_est, mean_deg

# -----------------------------------------------------------------------------
# 2. Loop Principal e Plotagem
# -----------------------------------------------------------------------------

def run_lambda_validation():
    N = 500
    m = 2
    # Esticamos o range de lambda para forçar o grafo a reagir
    lambda_values = np.linspace(0.5, 6.0, 8)
    trials_per_lambda = 3

    results = {"lambda": [], "beta": [], "mean_deg": []}

    print("=== EPPQ λ-VALIDATION PIPELINE (BOLTZMANN) ===")
    print(f"N = {N}, m = {m}\n")

    for lam in lambda_values:
        beta_list = []
        deg_list = []
        for trial in range(trials_per_lambda):
            seed = 42 + int(lam * 10) + trial
            G, beta_est, mean_deg = pmah_vacuum_generator(N, m, lam, steps=8000, T=3.0, seed=seed)
            if G is not None:
                beta_list.append(beta_est)
                deg_list.append(mean_deg)

        if beta_list:
            avg_beta = np.mean(beta_list)
            avg_deg = np.mean(deg_list)
            results["lambda"].append(lam)
            results["beta"].append(avg_beta)
            results["mean_deg"].append(avg_deg)
            print(f"λ = {lam:.2f} -> β = {avg_beta:.3f}, ⟨d⟩ = {avg_deg:.2f}, β⟨d⟩ = {avg_beta * avg_deg:.3f}")

    return results

def analyze_and_plot(results):
    lambdas = np.array(results["lambda"])
    betas = np.array(results["beta"])
    mean_degs = np.array(results["mean_deg"])
    product = betas * mean_degs

    coeffs = np.polyfit(product, lambdas, 1)
    K_fit = coeffs[0]
    intercept = coeffs[1]

    product_fit = np.linspace(min(product), max(product), 100)
    lambda_fit = K_fit * product_fit + intercept

    plt.figure(figsize=(8, 6))
    plt.scatter(product, lambdas, color='blue', s=80, label='Simulações PMAH (Boltzmann)')
    plt.plot(product_fit, lambda_fit, 'r--', label=rf'Ajuste: $\lambda = {K_fit:.3f} \cdot \beta\langle d \rangle + {intercept:.3f}$')

    # Correção dos Raw Strings (r'') para evitar o SyntaxWarning
    plt.xlabel(r'$\beta \cdot \langle d \rangle$', fontsize=14)
    plt.ylabel(r'$\lambda$ (Inércia Histórica)', fontsize=14)
    plt.title(r'Validação Dinâmica da Constante Fundamental de Inércia', fontsize=16)

    plt.legend()
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig('lambda_validation_final.png', dpi=150)
    plt.show()

    print("\n=== RESULTADOS DA VALIDAÇÃO ===")
    print(f"Constante K extraída: {K_fit:.4f}")
    print(f"Intercepto: {intercept:.4f}")
    print(f"Coeficiente de correlação R²: {np.corrcoef(product, lambdas)[0,1]**2:.4f}")

    return K_fit

if __name__ == "__main__":
    results = run_lambda_validation()
    K = analyze_and_plot(results)